version: '3.9'

services:
  app:
    container_name: ec_api
    build:
      context: src
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/go/src
    depends_on:
      - db
    networks:
      - ec_backend

  db:
    container_name: ec_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - ec_backend
  
  nginx:
    container_name: ec_proxy
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - ec_backend

networks:
  ec_backend:

volumes:
  data: