# GitHub Actions to build and test Go application
name: Build Go application

# Defines events to trigger the GitHub Actions
# Push and pull request to main branch trigger this workflows
on:
  push:
    branches: main
  pull_request:
    branches: main

# Defines the workflows
jobs:
  Build:
    runs-on: ubuntu-latest
    # Set the default working directory to /src
    defaults:
      run:
        working-directory: ./src

    # A series of steps this workflows perform
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Golang with a specified version
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build

      - name: Test
        run: go test
